name: query_builder
description: Dart package to simplify database interaction
version: 0.1.2
author: Aidan Murphey <amurphey7@gmail.com>
homepage: https://aidanmurphey.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mysql1: ^0.17.0
